name: Github AWS OIDC
on:
  push:
    branches:
      - main

env:
  AWS_REGION: "us-east-2"

permissions:
  id-token: write
  contents: read
# Main job to test credentials
jobs:
  oidc-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Test AWS Credentials
        run: aws sts get-caller-identity
