name: Github AWS OIDC
on:
  push:
    branches:
      - main
# Environment variables
env:
  AWS_REGION: "us-east-2"

permissions:
  id-token: write
  contents: read
# Main job to test credentials
jobs:
  oidc-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          role-to-assume: arn:aws:iam::481665093940:role/github-action-role
          aws-region: us-east-2
      - name: Test AWS Credentials
        run: aws sts get-caller-identity
